
services:
  app:
    build: ./app
    ports:
      - "5000:5000"
      - "5678:5678"
    volumes:
      - ./:/app
      - ./docs:/app/docs
    env_file:
      - .env
    environment:
      ENV: development
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Desactiva la seguridad para evitar problemas con certificados en desarrollo
      - network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
